{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "1cai-stack.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "1cai-stack.name" . }}
{{- end }}
